# Generated by Django 4.2.2 on 2023-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assignees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [models.Case(models.When(priority='critical', then=models.Value(1)), models.When(priority='urgent', then=models.Value(2)), models.When(priority='normal', then=models.Value(3)), default=models.Value(3), output_field=models.IntegerField())], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
